
#java version
FROM openjdk:17-jdk-slim
# Set the working directory
WORKDIR /app
# Copy the JAR file into the container
COPY target/*.jar app.jar
# Expose the port the app runs on
EXPOSE 8081
# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
# Use the default command to run the application
#CMD ["java", "-jar", "app.jar"]
# Note: The CMD line is commented out because ENTRYPOINT is already set to run the application.
